version: '3.8'

services:
  web:
    build: .
    container_name: final_spiders
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    restart: unless-stopped
